flowchart LR
    User["Cliente"] --> ListAvailable["Lista de eventos"]
    User --> Evaluation["Avaliação de Evento"]
    Adm["Administrador"] --> EReg["Registro de Eventos"]
    Buy --> Email["Email"]
    User --> Buy["Compra de ingressos"]
    User --> Refund["Sistema de Reembolso"]
    Email -- notifica --> User
    Refund --> Email
    
    User --> UsSys["Registro de Usuário"]
    User ---> UsEdit["Edição de Usuário"]
    
    Adm --> AdmSys["Registro de Administrador"]
    Adm --> UsEdit

    User@{ icon: "fa:circle-user", pos: "b"}
    Adm@{ icon: "fa:circle-user", pos: "b"}


