name: Java CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 22
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '22'

    - name: Set up Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: '7.3.3' 

    - name: Grant execute permission for Gradle
      run: chmod +x gradlew

    - name: Build with Gradle
      run: gradle build

    - name: Run Tests
      run: gradle test

    - name: Generate Code Coverage
      run: gradle jacocoTestReport

    - name: Upload Test Results and Coverage
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: build/reports/tests/test

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        file: ./build/reports/jacoco/test/jacocoTestReport.xml
        fail_ci_if_error: true
        verbose: true
